# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'LazyLoadingList' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for LazyLoadingList
  pod 'SnapKit', '~> 5.6.0'

end
